//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionPractice.Components
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProductionPracticeEntities : DbContext
    {
        public ProductionPracticeEntities()
            : base("name=ProductionPracticeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BoughtCourse> BoughtCourse { get; set; }
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<Course_Tag> Course_Tag { get; set; }
        public virtual DbSet<KnowledgeLevel> KnowledgeLevel { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<SellHistory> SellHistory { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tag> Tag { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
